import React,{useEffect,useMemo,useRef,useState}from'react'
import{Badge,Box,Button,Flex,FormControl,FormLabel,Grid,Heading,Input,Modal,ModalBody,ModalCloseButton,ModalContent,ModalFooter,ModalHeader,ModalOverlay,Select,Spinner,Stack,Table,Tbody,Td,Text,Th,Thead,Tr}from'@chakra-ui/react'
import QRCode from'react-qr-code'
import api from'../services/api'
import{confirmAction,requestReason,useToast}from'../services/alerts'
import{peruDate,peruTime}from'../utils/date'
import QrCameraScanner from'../components/QrCameraScanner'

const statusNames={pending:'Pendiente',in_progress:'En proceso',supervisor_closed:'Cerrado por supervisor',rrhh_observed:'Observado por RRHH',rrhh_approved:'Aprobado por RRHH',reopened:'Reabierto',cancelled:'Anulado'}
const validationNames={confirmed:'Confirmado',observed:'Observado',annulled:'Anulado',impersonation:'Posible suplantación'}
const today=peruDate()
const LEGAL_SHIFT_MINUTES=9*60
const minutesBetween=(start,end)=>{if(!start||!end)return null;const diff=Math.round((new Date(end)-new Date(start))/60000);return Number.isFinite(diff)&&diff>=0?diff:null}
const formatHours=minutes=>minutes==null?'Pendiente':`${Math.floor(minutes/60)}h ${String(minutes%60).padStart(2,'0')}m`
const extraMinutes=p=>{const total=minutesBetween(p.entryAt,p.exitAt);return total==null?null:Math.max(total-LEGAL_SHIFT_MINUTES,0)}
export default function Attendance(){
 const user=JSON.parse(localStorage.getItem('user')||'null'),toast=useToast(),isWorker=user?.role==='colaborador',canSupervise=['admin','supervisor'].includes(user?.role),canReview=['admin','rrhh'].includes(user?.role)
 const[items,setItems]=useState([]),[selected,setSelected]=useState(null),[lastSync,setLastSync]=useState(null),[loading,setLoading]=useState(true),[clients,setClients]=useState([]),[sites,setSites]=useState([]),[areas,setAreas]=useState([]),[shifts,setShifts]=useState([]),[form,setForm]=useState({clientId:'',siteId:'',areaId:'',shiftId:'',attendanceDate:today}),[qr,setQr]=useState(null),[qrType,setQrType]=useState('entry'),[scannerCode,setScannerCode]=useState(''),[manualOpen,setManualOpen]=useState(false),[manual,setManual]=useState({collaboratorId:'',markingType:'entry',reason:'',observation:''}),[token,setToken]=useState(''),[scanning,setScanning]=useState(false),[lastMark,setLastMark]=useState(null),[saving,setSaving]=useState(false)
 const scannerRef=useRef(null)
 const load=()=>{if(isWorker){setLoading(false);return}setLoading(true);Promise.all([api.get('/attendance'),api.get('/organization/clients'),api.get('/organization/sites'),api.get('/core/areas'),api.get('/operational/shifts')]).then(([a,c,s,ar,sh])=>{setItems(a.data);setClients(c.data);setSites(s.data);setAreas(ar.data);setShifts(sh.data)}).catch(e=>toast({title:'No se pudo cargar el tareo',description:e.response?.data?.error,status:'error'})).finally(()=>setLoading(false))}
 useEffect(load,[])
 const availableSites=useMemo(()=>sites.filter(x=>!form.clientId||x.clientId===Number(form.clientId)),[sites,form.clientId])
 const openSheet=async(id,keepQr=false)=>{try{const{data}=await api.get(`/attendance/${id}`);setSelected(data);setLastSync(new Date());if(!keepQr)setQr(null)}catch(e){toast({title:'No se pudo abrir el tareo',description:e.response?.data?.error,status:'error'})}}
 useEffect(()=>{const sheetId=selected?.sheet?.id;if(!sheetId||!['in_progress','reopened'].includes(selected.sheet.status))return undefined;const timer=setInterval(async()=>{try{const{data}=await api.get(`/attendance/${sheetId}`);setSelected(current=>current?.sheet?.id===sheetId?data:current);setLastSync(new Date())}catch{/* El siguiente ciclo reintentará sin interrumpir al supervisor. */}},3000);return()=>clearInterval(timer)},[selected?.sheet?.id,selected?.sheet?.status])
 useEffect(()=>{if(!selected?.sheet?.id||scannerCode.trim().length<8)return undefined;const timer=setTimeout(()=>scanCode(scannerCode),180);return()=>clearTimeout(timer)},[scannerCode])
 const start=async()=>{setSaving(true);try{const{data}=await api.post('/attendance',{...form,clientId:Number(form.clientId),siteId:Number(form.siteId),areaId:Number(form.areaId),shiftId:Number(form.shiftId)});toast({title:'Tareo iniciado',status:'success'});setSelected(data);load()}catch(e){toast({title:'No se pudo iniciar',description:e.response?.data?.error,status:'error'})}finally{setSaving(false)}}
 const generateQr=async()=>{try{const{data}=await api.post(`/attendance/${selected.sheet.id}/qr`,{markingType:qrType});setQr(data);toast({title:'QR temporal generado',description:`Válido hasta ${peruTime(data.expiresAt)}`,status:'success'})}catch(e){toast({title:'No se pudo generar el QR',description:e.response?.data?.error,status:'error'})}}
 const scanCode=async codeValue=>{const code=String(codeValue||scannerCode).trim();if(!code||saving)return;setSaving(true);try{const{data}=await api.post(`/attendance/${selected.sheet.id}/scan-code`,{code,markingType:qrType,deviceInfo:'laser-scanner'});setLastMark({markedAt:data.markedAt,markingType:data.markingType,minutesLate:data.minutesLate});toast({title:'Lectura registrada',description:`${qrType==='entry'?'Ingreso':qrType==='exit'?'Salida':'Presencia'} registrada`,status:'success'});setScannerCode('');openSheet(selected.sheet.id,true)}catch(e){setLastMark(null);toast({title:'Lectura rechazada',description:e.response?.data?.error,status:'error'});setScannerCode('')}finally{setSaving(false)}}
 const mark=async scannedToken=>{const qrToken=String(scannedToken||token).trim();if(!qrToken)return;setScanning(false);setSaving(true);let location={};try{location=await new Promise(resolve=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude}),()=>resolve({}),{timeout:5000,enableHighAccuracy:true}):resolve({}))}catch{location={}}try{const{data}=await api.post('/attendance/scan',{token:qrToken,deviceInfo:navigator.userAgent,...location});setLastMark({markedAt:data.markedAt,markingType:data.markingType,minutesLate:data.minutesLate});toast({title:'Asistencia registrada correctamente',status:'success'});setToken('')}catch(e){setLastMark(null);toast({title:'Marcación rechazada',description:e.response?.data?.error,status:'error'})}finally{setSaving(false)}}
 const saveManual=async()=>{setSaving(true);try{await api.post(`/attendance/${selected.sheet.id}/manual`,manual);toast({title:'Marcación manual registrada',status:'success'});setManualOpen(false);openSheet(selected.sheet.id)}catch(e){toast({title:'No se pudo registrar',description:e.response?.data?.error,status:'error'})}finally{setSaving(false)}}
 const validate=async(person,validation)=>{let observation='';if(['observed','impersonation'].includes(validation)){observation=await requestReason({title:validation==='impersonation'?'Reportar posible suplantación':'Observar marcación',label:'Detalle de la observación',confirmText:'Registrar'});if(!observation)return}try{const{data}=await api.patch(`/attendance/${selected.sheet.id}/people/${person.collaboratorId}/validation`,{validation,observation});setSelected(data);setLastSync(new Date());toast({title:validation==='confirmed'?'Presencia confirmada':validation==='observed'?'Marcación observada':'Posible suplantación reportada',status:validation==='confirmed'?'success':'warning'})}catch(e){toast({title:'No se pudo validar',description:e.response?.data?.error,status:'error'})}}
 const close=async()=>{if(!await confirmAction({title:'Cerrar tareo',text:'Después del cierre el supervisor no podrá modificarlo.',confirmText:'Cerrar tareo',icon:'warning'}))return;try{const{data}=await api.post(`/attendance/${selected.sheet.id}/close`);toast({title:'Tareo cerrado',description:`${data.warnings.pending} sin ingreso y ${data.warnings.missingExits} sin salida.`,status:'success'});openSheet(selected.sheet.id);load()}catch(e){toast({title:'No se pudo cerrar',description:e.response?.data?.error,status:'error'})}}
 const review=async status=>{try{await api.patch(`/attendance/${selected.sheet.id}/review`,{status});toast({title:'Revisión actualizada',status:'success'});openSheet(selected.sheet.id);load()}catch(e){toast({title:'No se pudo revisar',description:e.response?.data?.error,status:'error'})}}
 if(isWorker)return <Box maxW="560px" mx="auto" pb={8}><Box textAlign="center" mb={6}><Text color="teal.600" fontWeight="700" fontSize="sm">MI ASISTENCIA</Text><Heading size="lg" mt={1}>Registrar marcación</Heading><Text color="gray.500" mt={2}>Escanea el QR mostrado por tu supervisor.</Text></Box>{lastMark&&<Box bg="green.50" borderWidth="1px" borderColor="green.200" borderRadius="xl" p={5} mb={5} textAlign="center"><Text fontSize="3xl">✓</Text><Heading size="md" color="green.700">Marcación registrada</Heading><Text mt={2}>{lastMark.markingType==='entry'?'Ingreso':lastMark.markingType==='exit'?'Salida':'Presencia'} · {peruTime(lastMark.markedAt)}</Text>{lastMark.minutesLate>0&&<Badge colorScheme="orange" mt={2}>{lastMark.minutesLate} min de tardanza</Badge>}</Box>}<Box bg="white" borderWidth="1px" borderRadius="xl" p={{base:4,md:6}} boxShadow="sm">{scanning?<><QrCameraScanner active={scanning} onScan={mark}/><Button mt={4} w="100%" variant="outline" onClick={()=>setScanning(false)}>Cancelar escaneo</Button></>:<Button h="64px" w="100%" colorScheme="teal" fontSize="lg" onClick={()=>{setLastMark(null);setScanning(true)}} isLoading={saving}>Abrir cámara y escanear</Button>}<Flex align="center" gap={3} my={5}><Box h="1px" bg="gray.200" flex="1"/><Text fontSize="sm" color="gray.500">o ingresar manualmente</Text><Box h="1px" bg="gray.200" flex="1"/></Flex><FormControl><FormLabel>Token temporal</FormLabel><Input value={token} onChange={e=>setToken(e.target.value.trim())} placeholder="Pega aquí el token del QR"/></FormControl><Button mt={3} w="100%" variant="outline" onClick={()=>mark()} isLoading={saving} isDisabled={!token}>Registrar con token</Button><Text fontSize="xs" color="gray.500" mt={4} textAlign="center">La cámara y ubicación requieren autorización del dispositivo. El QR expira automáticamente.</Text></Box></Box>
 if(loading)return <Flex justify="center" py={16}><Spinner/></Flex>
 if(selected){const{sheet,people}=selected,editable=['in_progress','reopened'].includes(sheet.status);return <Box><Flex direction={{base:'column',md:'row'}} justify="space-between" gap={4} mb={6}><Box><Button size="sm" variant="ghost" onClick={()=>{setSelected(null);setQr(null)}}>← Volver</Button><Heading size="lg" mt={2}>Tareo · {sheet.siteName}</Heading><Text color="gray.500">{String(sheet.attendanceDate).slice(0,10)} · {sheet.areaName} · {sheet.shiftName}</Text><Text fontSize="xs" color="teal.600" mt={1}>Actualización automática cada 3 segundos{lastSync?` · ${peruTime(lastSync)}`:''}</Text></Box><Badge alignSelf={{base:'start',md:'center'}} colorScheme={sheet.status==='rrhh_approved'?'green':sheet.status==='supervisor_closed'?'blue':'orange'} px={3} py={2}>{statusNames[sheet.status]}</Badge></Flex>
 {canSupervise&&editable&&<Grid templateColumns={{base:'1fr',lg:'320px 1fr'}} gap={5} mb={6}><Box bg="white" borderWidth="1px" borderRadius="xl" p={5}><Heading size="sm" mb={4}>QR dinámico</Heading><Flex gap={2}><Select value={qrType} onChange={e=>setQrType(e.target.value)}><option value="entry">Ingreso</option><option value="exit">Salida</option><option value="presence">Presencia</option></Select><Button colorScheme="teal" onClick={generateQr}>Generar</Button></Flex>{qr&&<Box mt={5} textAlign="center"><Box bg="white" p={4} display="inline-block"><QRCode value={qr.token} size={190}/></Box><Text fontSize="sm" color="gray.500" mt={2}>Expira: {peruTime(qr.expiresAt)}</Text></Box>}</Box><Box bg="white" borderWidth="1px" borderRadius="xl" p={5}><Heading size="sm">Escaneo rápido DNI/Fotocheck</Heading><Text color="gray.500" mt={2}>La pistola escribe el código y registra automáticamente según el tipo seleccionado arriba.</Text><Input ref={scannerRef} mt={4} size="lg" bg="gray.50" value={scannerCode} onChange={e=>setScannerCode(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')scanCode(e.currentTarget.value)}} placeholder="Escanear DNI o fotocheck" autoComplete="off"/><Text fontSize="xs" color="gray.500" mt={2}>Si se lee dos veces, se conserva la primera lectura.</Text><Flex gap={3} mt={5} wrap="wrap"><Button onClick={()=>setManualOpen(true)}>Marcación manual</Button><Button colorScheme="red" variant="outline" onClick={close}>Cerrar tareo</Button></Flex></Box></Grid>}
 {canReview&&['supervisor_closed','rrhh_observed'].includes(sheet.status)&&<Flex bg="blue.50" borderRadius="xl" p={4} gap={3} mb={5} wrap="wrap"><Text fontWeight="700" alignSelf="center" mr="auto">Revisión RRHH</Text><Button size="sm" onClick={()=>review('rrhh_observed')}>Observar</Button><Button size="sm" onClick={()=>review('reopened')}>Reabrir</Button><Button size="sm" colorScheme="green" onClick={()=>review('rrhh_approved')}>Aprobar</Button><Button size="sm" colorScheme="red" variant="outline" onClick={()=>review('cancelled')}>Anular</Button></Flex>}
 <Box className="rrhh-table-scroll" bg="white" borderWidth="1px" borderRadius="xl"><Table><Thead><Tr><Th>Colaborador</Th><Th>Cargo</Th><Th>Ingreso</Th><Th>Salida</Th><Th>Horas ingreso-salida</Th><Th>Horas extra</Th><Th>Estado</Th><Th>Validación visual</Th></Tr></Thead><Tbody>{people.map(p=>{const total=minutesBetween(p.entryAt,p.exitAt),extra=extraMinutes(p);return <Tr key={p.collaboratorId}><Td fontWeight="600">{p.lastName}, {p.firstName}<Text fontSize="xs">{p.employeeCode}</Text></Td><Td>{p.positionName}</Td><Td>{p.entryAt?peruTime(p.entryAt):'Pendiente'}</Td><Td>{p.exitAt?peruTime(p.exitAt):'Pendiente'}</Td><Td>{formatHours(total)}<Text fontSize="xs" color="gray.500">Legal: 8h + 1h almuerzo</Text></Td><Td><Badge colorScheme={extra>0?'orange':'green'}>{extra==null?'Pendiente':formatHours(extra)}</Badge></Td><Td><Badge>{p.statusName||'Sin marcar'}</Badge></Td><Td>{canSupervise&&editable?<Box><Badge mb={2} colorScheme={p.supervisorValidation==='confirmed'?'green':p.supervisorValidation==='impersonation'?'red':p.supervisorValidation==='observed'?'orange':'gray'}>{!p.entryAt?'Esperando ingreso':p.supervisorValidation==='confirmed'?'Confirmado':p.supervisorValidation==='observed'?'Observado':p.supervisorValidation==='impersonation'?'Posible suplantación':'Sin validar'}</Badge><Flex gap={2}><Button size="xs" isDisabled={!p.entryAt} colorScheme="green" variant={p.supervisorValidation==='confirmed'?'solid':'outline'} onClick={()=>validate(p,'confirmed')}>Confirmar</Button><Button size="xs" isDisabled={!p.entryAt} colorScheme="orange" variant={p.supervisorValidation==='observed'?'solid':'outline'} onClick={()=>validate(p,'observed')}>Observar</Button><Button size="xs" isDisabled={!p.entryAt} colorScheme="red" variant={p.supervisorValidation==='impersonation'?'solid':'outline'} onClick={()=>validate(p,'impersonation')}>Suplantación</Button></Flex>{p.observation&&<Text fontSize="xs" color="gray.500" mt={2}>{p.observation}</Text>}</Box>:validationNames[p.supervisorValidation]||'—'}</Td></Tr>})}</Tbody></Table></Box>
 <Modal isOpen={manualOpen} onClose={()=>setManualOpen(false)} isCentered><ModalOverlay/><ModalContent><ModalHeader>Marcación manual de contingencia</ModalHeader><ModalCloseButton/><ModalBody><Stack spacing={4}><FormControl isRequired><FormLabel>Colaborador</FormLabel><Select value={manual.collaboratorId} onChange={e=>setManual({...manual,collaboratorId:Number(e.target.value)})}><option value="">Seleccionar</option>{people.map(p=><option key={p.collaboratorId} value={p.collaboratorId}>{p.lastName}, {p.firstName}</option>)}</Select></FormControl><FormControl><FormLabel>Tipo</FormLabel><Select value={manual.markingType} onChange={e=>setManual({...manual,markingType:e.target.value})}><option value="entry">Ingreso</option><option value="exit">Salida</option><option value="presence">Presencia</option></Select></FormControl><FormControl isRequired><FormLabel>Motivo de contingencia</FormLabel><Input value={manual.reason} onChange={e=>setManual({...manual,reason:e.target.value})}/></FormControl><FormControl><FormLabel>Observación</FormLabel><Input value={manual.observation} onChange={e=>setManual({...manual,observation:e.target.value})}/></FormControl></Stack></ModalBody><ModalFooter><Button variant="ghost" mr={3} onClick={()=>setManualOpen(false)}>Cancelar</Button><Button colorScheme="teal" onClick={saveManual} isLoading={saving}>Registrar</Button></ModalFooter></ModalContent></Modal></Box>}
 return <Box><Flex direction={{base:'column',md:'row'}} justify="space-between" gap={4} mb={7}><Box><Heading size="lg">Tareo de asistencias</Heading><Text color="gray.500" mt={2}>Control diario por cliente, sede, área y turno.</Text></Box></Flex>{canSupervise&&<Box bg="white" borderWidth="1px" borderRadius="xl" p={5} mb={6}><Heading size="md" mb={4}>Iniciar turno</Heading><Grid templateColumns={{base:'1fr',md:'repeat(3,1fr)'}} gap={4}><FormControl><FormLabel>Cliente</FormLabel><Select value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value,siteId:''})}><option value="">Seleccionar</option>{clients.map(x=><option key={x.id} value={x.id}>{x.tradeName||x.businessName}</option>)}</Select></FormControl><FormControl><FormLabel>Sede</FormLabel><Select value={form.siteId} onChange={e=>setForm({...form,siteId:e.target.value})}><option value="">Seleccionar</option>{availableSites.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></FormControl><FormControl><FormLabel>Área</FormLabel><Select value={form.areaId} onChange={e=>setForm({...form,areaId:e.target.value})}><option value="">Seleccionar</option>{areas.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></FormControl><FormControl><FormLabel>Turno</FormLabel><Select value={form.shiftId} onChange={e=>setForm({...form,shiftId:e.target.value})}><option value="">Seleccionar</option>{shifts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></FormControl><FormControl><FormLabel>Fecha</FormLabel><Input type="date" value={form.attendanceDate} onChange={e=>setForm({...form,attendanceDate:e.target.value})}/></FormControl><Button alignSelf="end" colorScheme="teal" onClick={start} isLoading={saving}>Iniciar tareo</Button></Grid></Box>}<Box className="rrhh-table-scroll" bg="white" borderWidth="1px" borderRadius="xl"><Table><Thead><Tr><Th>Fecha</Th><Th>Cliente / sede</Th><Th>Área / turno</Th><Th>Supervisor</Th><Th>Avance</Th><Th>Estado</Th><Th/></Tr></Thead><Tbody>{items.map(x=><Tr key={x.id}><Td>{String(x.attendanceDate).slice(0,10)}</Td><Td>{x.clientName}<Text fontSize="xs">{x.siteName}</Text></Td><Td>{x.areaName}<Text fontSize="xs">{x.shiftName}</Text></Td><Td>{x.supervisorName}</Td><Td>{x.markedCount}/{x.expectedCount}</Td><Td><Badge>{statusNames[x.status]}</Badge></Td><Td><Button size="sm" onClick={()=>openSheet(x.id)}>Abrir</Button></Td></Tr>)}</Tbody></Table></Box></Box>
}

