import React,{useEffect,useMemo,useState}from'react'
import{Badge,Box,Button,Flex,FormControl,FormLabel,Grid,Heading,Input,Modal,ModalBody,ModalCloseButton,ModalContent,ModalFooter,ModalHeader,ModalOverlay,Select,Spinner,Tab,TabList,TabPanel,TabPanels,Tabs,Table,Tbody,Td,Text,Th,Thead,Tr}from'@chakra-ui/react'
import{DeleteIcon,EditIcon}from'@chakra-ui/icons'
import api from'../services/api'
import{confirmAction,useToast}from'../services/alerts'
import{peruDate}from'../utils/date'

const ruleEmpty={name:'',areaId:'',bonusTypeId:'',calculationMode:'fixed',baseSource:'salary',fixedAmount:'',percentage:'',monthlyBonusBase:'',minAttendanceDays:0,maxAbsences:0,maxLateArrivals:0,minSeniorityDays:0,entryWindowDays:30,productivityMin:'',productivityMax:'',validFrom:peruDate(),validTo:'',ruleStatus:'active'}
const campaignEmpty={name:'',periodId:'',clientId:'',siteId:'',areaId:'',bonusTypeId:'',ruleId:''}
const periodName=referenceMonth=>{const[y,m]=String(referenceMonth).split('-').map(Number),months=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];return y&&m?`Periodo ${months[m-1]} ${y}`:''}
const emptyPeriod=()=>{const referenceMonth=peruDate().slice(0,7);return{name:periodName(referenceMonth),referenceMonth,half:1}}
const campaignStatuses={draft:'Borrador',active:'Activa',calculating:'En cálculo',calculated:'Calculada',in_review:'En revisión',approved:'Aprobada',observed:'Observada',closed:'Cerrada',cancelled:'Anulada'}
const ruleStatuses={draft:'Borrador',active:'Activa',inactive:'Inactiva'}
const date=value=>String(value||'').slice(0,10)

export default function Bonuses(){
 const user=JSON.parse(localStorage.getItem('user')||'null'),toast=useToast()
 const[settings,setSettings]=useState({paymentFrequency:'monthly',cutoffDay:15}),[periods,setPeriods]=useState([]),[campaigns,setCampaigns]=useState([]),[rules,setRules]=useState([]),[types,setTypes]=useState([]),[areas,setAreas]=useState([]),[clients,setClients]=useState([]),[sites,setSites]=useState([])
 const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[periodOpen,setPeriodOpen]=useState(false),[campaignOpen,setCampaignOpen]=useState(false),[ruleOpen,setRuleOpen]=useState(false),[editingRuleId,setEditingRuleId]=useState(null),[detail,setDetail]=useState(null)
 const[period,setPeriod]=useState(emptyPeriod),[campaign,setCampaign]=useState(campaignEmpty),[rule,setRule]=useState(ruleEmpty),[productivity,setProductivity]=useState({})
 const load=()=>{setLoading(true);Promise.all([api.get('/bonuses/settings'),api.get('/bonuses/periods'),api.get('/bonuses/campaigns'),api.get('/bonuses/rules'),api.get('/bonuses/types'),api.get('/core/areas'),api.get('/organization/clients'),api.get('/organization/sites')]).then(([cfg,p,c,r,t,a,cl,s])=>{setSettings(cfg.data);setPeriods(p.data);setCampaigns(c.data);setRules(r.data);setTypes(t.data);setAreas(a.data);setClients(cl.data);setSites(s.data)}).catch(e=>toast({title:'No se pudo cargar Bonos',description:e.response?.data?.error,status:'error'})).finally(()=>setLoading(false))}
 useEffect(load,[])
 const filteredSites=useMemo(()=>sites.filter(x=>!campaign.clientId||x.clientId===Number(campaign.clientId)),[sites,campaign.clientId])
 const filteredRules=useMemo(()=>rules.filter(x=>(!campaign.areaId||x.areaId===Number(campaign.areaId))&&(!campaign.bonusTypeId||x.bonusTypeId===Number(campaign.bonusTypeId))&&x.ruleStatus==='active'),[rules,campaign.areaId,campaign.bonusTypeId])
 const isEntry=types.find(x=>x.id===Number(rule.bonusTypeId))?.code==='ENTRY'
 const run=async(work,success,error,done)=>{setSaving(true);try{await work();toast({title:success,status:'success'});done?.();load()}catch(e){toast({title:error,description:e.response?.data?.error,status:'error'})}finally{setSaving(false)}}
 const savePeriod=()=>run(()=>api.post('/bonuses/periods',period),'Periodo abierto','No se pudo abrir el periodo',()=>{setPeriodOpen(false);setPeriod(emptyPeriod())})
 const closePeriod=async x=>{if(await confirmAction({title:'Cerrar periodo',text:'Las campañas y resultados quedarán bloqueados.',confirmText:'Cerrar periodo',icon:'warning'}))run(()=>api.patch(`/bonuses/periods/${x.id}/close`),'Periodo cerrado','No se pudo cerrar el periodo')}
 const saveCampaign=()=>run(()=>api.post('/bonuses/campaigns',campaign),'Campaña creada y activada','No se pudo crear la campaña',()=>{setCampaignOpen(false);setCampaign(campaignEmpty)})
 const saveRule=()=>run(()=>editingRuleId?api.put(`/bonuses/rules/${editingRuleId}`,rule):api.post('/bonuses/rules',rule),editingRuleId?'Regla actualizada':'Regla creada','No se pudo guardar la regla',()=>{setRuleOpen(false);setEditingRuleId(null);setRule(ruleEmpty)})
 const editRule=x=>{setEditingRuleId(x.id);setRule({...ruleEmpty,...x,validFrom:date(x.validFrom),validTo:x.validTo?date(x.validTo):'',productivityMin:x.productivityMin??'',productivityMax:x.productivityMax??''});setRuleOpen(true)}
 const openDetail=async id=>{try{const{data}=await api.get(`/bonuses/campaigns/${id}`);setDetail(data);setProductivity(Object.fromEntries(data.results.map(x=>[x.collaboratorId,x.productivityFactor??''])))}catch(e){toast({title:'No se pudo abrir',description:e.response?.data?.error,status:'error'})}}
 const calculate=()=>run(async()=>{const{data}=await api.post(`/bonuses/campaigns/${detail.campaign.id}/calculate`,{productivity});setDetail(data)},'Cálculo ejecutado','No se pudo calcular')
 const approve=()=>run(async()=>{const{data}=await api.patch(`/bonuses/campaigns/${detail.campaign.id}/approve`);setDetail(data)},'Campaña aprobada por Gerencia','No se pudo aprobar')
 const removeCampaign=async x=>{if(await confirmAction({title:'Eliminar campaña',text:'La campaña se anulará y quedará auditada.',confirmText:'Sí, eliminar',icon:'warning'}))run(()=>api.delete(`/bonuses/campaigns/${x.id}`),'Campaña eliminada','No se pudo eliminar')}
 if(loading)return <Flex justify="center" py={16}><Spinner/></Flex>
 return <Box>
  <Heading size="lg">Bonos</Heading><Text color="gray.500" mt={2} mb={7}>Periodos, campañas, cálculo, revisión y aprobación.</Text>
  <Tabs colorScheme="teal"><TabList><Tab>Periodos</Tab><Tab>Campañas</Tab><Tab>Reglas por área</Tab></TabList><TabPanels>
   <TabPanel px={0}><Flex justify="flex-end" mb={4}><Button colorScheme="teal" onClick={()=>setPeriodOpen(true)}>Abrir periodo</Button></Flex><Card><Table><Thead><Tr><Th>Periodo</Th><Th>Frecuencia</Th><Th>Fechas</Th><Th>Campañas</Th><Th>Estado</Th><Th/></Tr></Thead><Tbody>{periods.map(x=><Tr key={x.id}><Td fontWeight="600">{x.name}</Td><Td>{x.frequency==='biweekly'?'Quincenal':'Mensual'}</Td><Td>{date(x.periodStart)} - {date(x.periodEnd)}</Td><Td>{x.campaignCount}</Td><Td><Badge colorScheme={x.status==='open'?'green':'gray'}>{x.status==='open'?'Abierto':'Cerrado'}</Badge></Td><Td>{x.status==='open'&&['admin','rrhh'].includes(user?.role)&&<Button size="sm" variant="outline" onClick={()=>closePeriod(x)}>Cerrar periodo</Button>}</Td></Tr>)}</Tbody></Table></Card></TabPanel>
   <TabPanel px={0}><Flex justify="flex-end" mb={4}><Button colorScheme="teal" isDisabled={!periods.some(x=>x.status==='open')} onClick={()=>setCampaignOpen(true)}>Nueva campaña</Button></Flex><Card><Table><Thead><Tr><Th>Campaña</Th><Th>Periodo</Th><Th>Cliente / Área</Th><Th>Tipo</Th><Th>Estado</Th><Th/></Tr></Thead><Tbody>{campaigns.map(x=><Tr key={x.id}><Td fontWeight="600">{x.name}</Td><Td>{x.periodName}</Td><Td>{x.clientName}<Text fontSize="xs">{x.areaName}</Text></Td><Td>{x.bonusTypeName}</Td><Td><Badge>{campaignStatuses[x.status]||x.status}</Badge></Td><Td><Flex gap={2}><Button size="sm" onClick={()=>openDetail(x.id)}>Revisar</Button>{['admin','rrhh'].includes(user?.role)&&!['approved','closed'].includes(x.status)&&<Button size="sm" colorScheme="red" variant="outline" leftIcon={<DeleteIcon/>} onClick={()=>removeCampaign(x)}>Eliminar</Button>}</Flex></Td></Tr>)}</Tbody></Table></Card></TabPanel>
   <TabPanel px={0}><Flex justify="flex-end" mb={4}><Button colorScheme="teal" onClick={()=>{setEditingRuleId(null);setRule(ruleEmpty);setRuleOpen(true)}}>Nueva regla</Button></Flex><Card><Table><Thead><Tr><Th>Regla</Th><Th>Área</Th><Th>Tipo</Th><Th>Cálculo</Th><Th>Estado</Th><Th/></Tr></Thead><Tbody>{rules.map(x=><Tr key={x.id}><Td fontWeight="600">{x.name}</Td><Td>{x.areaName}</Td><Td>{x.bonusTypeName}</Td><Td>{x.calculationMode==='fixed'?`S/ ${x.fixedAmount}`:`${x.percentage}% de ${x.baseSource==='salary'?'sueldo':'fondo mensual'}`}</Td><Td><Badge>{ruleStatuses[x.ruleStatus]||x.ruleStatus}</Badge></Td><Td>{['admin','rrhh'].includes(user?.role)&&<Button size="sm" variant="outline" leftIcon={<EditIcon/>} onClick={()=>editRule(x)}>Editar</Button>}</Td></Tr>)}</Tbody></Table></Card></TabPanel>
  </TabPanels></Tabs>
  <Modal isOpen={periodOpen} onClose={()=>setPeriodOpen(false)}><ModalOverlay/><ModalContent><ModalHeader>Abrir periodo de remuneraciones</ModalHeader><ModalCloseButton/><ModalBody><Grid gap={4}><F label="Nombre del periodo"><Input bg="gray.100" isReadOnly value={period.name}/></F><F label="Mes"><Input type="month" value={period.referenceMonth} onChange={e=>{const referenceMonth=e.target.value;setPeriod({...period,referenceMonth,name:periodName(referenceMonth)})}}/></F>{settings.paymentFrequency==='biweekly'&&<F label="Quincena"><Select value={period.half} onChange={e=>setPeriod({...period,half:Number(e.target.value)})}><option value={1}>Primera: día 1 al {settings.cutoffDay}</option><option value={2}>Segunda: día {Number(settings.cutoffDay)+1} al fin de mes</option></Select></F>}</Grid></ModalBody><Foot close={()=>setPeriodOpen(false)} save={savePeriod} saving={saving} text="Abrir periodo"/></ModalContent></Modal>
  <Modal isOpen={campaignOpen} onClose={()=>setCampaignOpen(false)} size="3xl"><ModalOverlay/><ModalContent><ModalHeader>Nueva campaña</ModalHeader><ModalCloseButton/><ModalBody><Grid templateColumns={{base:'1fr',md:'repeat(2,1fr)'}} gap={4}><F label="Nombre"><Input value={campaign.name} onChange={e=>setCampaign({...campaign,name:e.target.value})}/></F><F label="Periodo abierto"><Sel value={campaign.periodId} onChange={e=>setCampaign({...campaign,periodId:Number(e.target.value)})} data={periods.filter(x=>x.status==='open')}/></F><F label="Cliente"><Sel value={campaign.clientId} onChange={e=>setCampaign({...campaign,clientId:Number(e.target.value),siteId:''})} data={clients} name={x=>x.tradeName||x.businessName}/></F><F label="Sede"><Sel value={campaign.siteId} onChange={e=>setCampaign({...campaign,siteId:Number(e.target.value)})} data={filteredSites}/></F><F label="Área"><Sel value={campaign.areaId} onChange={e=>setCampaign({...campaign,areaId:Number(e.target.value),ruleId:''})} data={areas}/></F><F label="Tipo"><Sel value={campaign.bonusTypeId} onChange={e=>setCampaign({...campaign,bonusTypeId:Number(e.target.value),ruleId:''})} data={types}/></F><F label="Regla activa"><Sel value={campaign.ruleId} onChange={e=>setCampaign({...campaign,ruleId:Number(e.target.value)})} data={filteredRules}/></F></Grid></ModalBody><Foot close={()=>setCampaignOpen(false)} save={saveCampaign} saving={saving} text="Crear campaña"/></ModalContent></Modal>
  <Modal isOpen={ruleOpen} onClose={()=>setRuleOpen(false)} size="4xl"><ModalOverlay/><ModalContent><ModalHeader>{editingRuleId?'Editar':'Nueva'} regla de bono</ModalHeader><ModalCloseButton/><ModalBody><Grid templateColumns={{base:'1fr',md:'repeat(2,1fr)'}} gap={4}><F label="Nombre"><Input value={rule.name} onChange={e=>setRule({...rule,name:e.target.value})}/></F><F label="Área"><Sel value={rule.areaId} onChange={e=>setRule({...rule,areaId:Number(e.target.value)})} data={areas}/></F><F label="Tipo de bono"><Sel value={rule.bonusTypeId} onChange={e=>setRule({...rule,bonusTypeId:Number(e.target.value)})} data={types}/></F><F label="Modalidad"><Select value={rule.calculationMode} onChange={e=>setRule({...rule,calculationMode:e.target.value})}><option value="fixed">Monto fijo</option><option value="percentage">Porcentaje</option></Select></F>{rule.calculationMode==='fixed'?<Num label="Monto fijo" field="fixedAmount" data={rule} set={setRule}/>:<><Num label="Porcentaje" field="percentage" data={rule} set={setRule}/><F label="Base"><Select value={rule.baseSource} onChange={e=>setRule({...rule,baseSource:e.target.value})}><option value="salary">Sueldo</option><option value="monthly_bonus_base">Fondo mensual</option></Select></F></>}{isEntry?<Num label="Mínimo de días desde el ingreso" field="minSeniorityDays" data={rule} set={setRule}/>:<><Num label="Días asistidos mínimos" field="minAttendanceDays" data={rule} set={setRule}/><Num label="Máximo de faltas" field="maxAbsences" data={rule} set={setRule}/><Num label="Máximo de tardanzas" field="maxLateArrivals" data={rule} set={setRule}/><Num label="Antigüedad mínima (días)" field="minSeniorityDays" data={rule} set={setRule}/><Num label="Productividad mínima %" field="productivityMin" data={rule} set={setRule}/><Num label="Productividad máxima %" field="productivityMax" data={rule} set={setRule}/></>}<F label="Vigente desde"><Input type="date" value={rule.validFrom} onChange={e=>setRule({...rule,validFrom:e.target.value})}/></F><F label="Vigente hasta"><Input type="date" value={rule.validTo} onChange={e=>setRule({...rule,validTo:e.target.value})}/></F></Grid></ModalBody><Foot close={()=>setRuleOpen(false)} save={saveRule} saving={saving} text="Guardar regla"/></ModalContent></Modal>
  <Modal isOpen={Boolean(detail)} onClose={()=>setDetail(null)} size="6xl"><ModalOverlay/><ModalContent><ModalHeader>Detalle de cálculo</ModalHeader><ModalCloseButton/><ModalBody>{detail&&<><Text mb={4}>{detail.campaign.periodName} · {detail.campaign.name} · <Badge>{campaignStatuses[detail.campaign.status]||detail.campaign.status}</Badge></Text><Card><Table size="sm"><Thead><Tr><Th>Colaborador</Th>{detail.campaign.bonusTypeCode!=='ENTRY'&&<><Th>Productividad %</Th><Th>Asistencia</Th><Th>Faltas</Th><Th>Tardanzas</Th></>}<Th>Días</Th><Th>Elegible</Th><Th>Monto</Th></Tr></Thead><Tbody>{detail.results.map(x=><Tr key={x.id}><Td>{x.lastName}, {x.firstName}</Td>{detail.campaign.bonusTypeCode!=='ENTRY'&&<><Td><Input w="90px" size="sm" type="number" min="0" max="100" value={productivity[x.collaboratorId]??''} onChange={e=>setProductivity({...productivity,[x.collaboratorId]:e.target.value})}/></Td><Td>{x.attendanceDays}</Td><Td>{x.absences}</Td><Td>{x.lateArrivals}</Td></>}<Td>{x.seniorityDays}</Td><Td><Badge colorScheme={x.eligible?'green':'gray'}>{x.eligible?'Sí':'No'}</Badge></Td><Td>S/ {Number(x.calculatedAmount).toFixed(2)}</Td></Tr>)}</Tbody></Table></Card></>}</ModalBody><ModalFooter><Button mr={3} onClick={()=>setDetail(null)}>Cerrar</Button>{detail&&detail.campaign.periodStatus==='open'&&['active','in_review'].includes(detail.campaign.status)&&user?.role!=='gerencia'&&<Button colorScheme="teal" onClick={calculate} isLoading={saving}>Calcular / recalcular</Button>}{detail?.campaign.status==='in_review'&&user?.role==='gerencia'&&<Button colorScheme="green" onClick={approve}>Aprobar campaña</Button>}</ModalFooter></ModalContent></Modal>
 </Box>
}
const Card=({children})=><Box bg="white" borderWidth="1px" borderRadius="xl" overflowX="auto">{children}</Box>
const F=({label,children})=><FormControl><FormLabel>{label}</FormLabel>{children}</FormControl>
const Sel=({data=[],name=x=>x.name,...props})=><Select {...props}><option value="">Seleccionar</option>{data.map(x=><option key={x.id} value={x.id}>{name(x)}</option>)}</Select>
const Num=({label,field,data,set})=><F label={label}><Input type="number" min="0" value={data[field]} onChange={e=>set({...data,[field]:e.target.value})}/></F>
const Foot=({close,save,saving,text})=><ModalFooter><Button mr={3} variant="ghost" onClick={close}>Cancelar</Button><Button colorScheme="teal" onClick={save} isLoading={saving}>{text}</Button></ModalFooter>
