const AssignmentModel=require('../models/AssignmentModel'),CollaboratorModel=require('../models/CollaboratorModel'),ClientModel=require('../models/ClientModel'),SiteModel=require('../models/SiteModel'),ShiftModel=require('../models/ShiftModel'),CatalogModel=require('../models/CatalogModel'),peruDate=require('../utils/peruDate');
class AssignmentService{
 static getOperators(companyId){return AssignmentModel.getPersonnel(companyId)}
 static getHistory(id,companyId){return AssignmentModel.getHistory(id,companyId)}
 static async assignMany(data,companyId,userId){const collaboratorIds=[...new Set((data.collaboratorIds||[]).map(Number).filter(Boolean))];if(!collaboratorIds.length||!data.clientId||!data.siteId||!data.areaId||!data.shiftId||!data.startDate){const e=new Error('Selecciona personal, cliente, sede, area, turno y fecha');e.status=400;throw e}if(collaboratorIds.length>200){const e=new Error('Solo se permiten 200 colaboradores por asignacion');e.status=400;throw e}const [workers,client,site,area,shift]=await Promise.all([Promise.all(collaboratorIds.map(id=>CollaboratorModel.getById(id,companyId))),ClientModel.getById(Number(data.clientId),companyId),SiteModel.getById(Number(data.siteId),companyId),CatalogModel.getById('areas',companyId,Number(data.areaId)),ShiftModel.getById(Number(data.shiftId),companyId)]);if(workers.some(worker=>!worker||!['operario','supervisor'].includes(worker.positionCode))){const e=new Error('La seleccion solo puede contener operarios y supervisores');e.status=400;throw e}if(!client?.estado||!site?.estado||site.clientId!==Number(data.clientId)||!area?.estado||!shift?.estado){const e=new Error('Cliente, sede, area o turno no son validos para la empresa');e.status=400;throw e}const replaceExistingIds=workers.filter(worker=>worker.positionCode==='operario').map(worker=>worker.id);return AssignmentModel.assignMany({...data,collaboratorIds,replaceExistingIds,clientId:Number(data.clientId),siteId:Number(data.siteId),areaId:Number(data.areaId),shiftId:Number(data.shiftId)},companyId,userId)}
 static assign(data,companyId,userId){return this.assignMany({...data,collaboratorIds:[data.collaboratorId]},companyId,userId)}
 static async endAssignment(id,data,companyId){const result=await AssignmentModel.endAssignment(id,companyId,data.endDate||peruDate());if(!result){const e=new Error('Asignacion vigente no encontrada');e.status=404;throw e}return result}
}
module.exports=AssignmentService;
