const crypto=require('crypto'),Model=require('../models/AttendanceModel')
const fail=(message,status=400)=>{const e=new Error(message);e.status=status;throw e}
class AttendanceService{
 static list(companyId){return Model.list(companyId)}
 static async detail(id,companyId){const sheet=await Model.getSheet(id,companyId);if(!sheet)fail('Tareo no encontrado',404);return{sheet,people:await Model.expected(id,companyId)}}
 static async start(data,companyId,user,ip){if(!data.clientId||!data.siteId||!data.areaId||!data.shiftId||!data.attendanceDate)fail('Selecciona cliente, sede, área, turno y fecha');try{const sheet=await Model.createSheet(data,companyId,user.id);await Model.audit(companyId,sheet.id,'sheet_started',user.id,null,JSON.stringify(data),null,ip);return this.detail(sheet.id,companyId)}catch(e){if(e.number===2627||e.number===2601)fail('Ya existe un tareo para esta sede, área, turno y fecha',409);throw e}}
 static async generateQr(id,type,companyId,user,ip){if(!['entry','exit','presence'].includes(type))fail('Tipo de marcación no válido');const sheet=await Model.getSheet(id,companyId);if(!sheet)fail('Tareo no encontrado',404);if(!['in_progress','reopened'].includes(sheet.status))fail('El tareo no permite generar marcaciones',409);const settings=await Model.settings(companyId),token=crypto.randomBytes(32).toString('base64url'),hash=crypto.createHash('sha256').update(token).digest('hex'),expiresAt=new Date(Date.now()+(settings?.qrValidityMinutes||3)*60000);await Model.createQr(id,type,hash,expiresAt,user.id);await Model.audit(companyId,id,'qr_generated',user.id,null,JSON.stringify({type,expiresAt}),null,ip);return{token,expiresAt,markingType:type}}
 static async scan(data,companyId,user,ip){if(!data.token)fail('El token QR es obligatorio');const hash=crypto.createHash('sha256').update(data.token).digest('hex'),event=await Model.qrByHash(hash);if(!event||event.companyId!==companyId)fail('QR no válido',404);if(!event.active||new Date(event.expiresAt)<=new Date())fail('El QR expiró. Solicita uno nuevo',410);if(!['in_progress','reopened'].includes(event.sheetStatus))fail('El tareo está cerrado',409);const collaborator=await Model.collaboratorByUser(user.id,companyId);if(!collaborator||!collaborator.estado||collaborator.laborStatus!=='active')fail('Tu colaborador no está activo',403);if(!await Model.isExpected(event.sheetId,collaborator.id))fail('No estás asignado a este turno',403);const settings=await Model.settings(companyId);if(settings?.requireGps&&(!data.latitude||!data.longitude))fail('Esta empresa requiere ubicación GPS');let minutesLate=0,statusCode='PRESENT';if(event.markingType==='entry'){const start=new Date(`${String(event.attendanceDate).slice(0,10)}T${String(event.startTime).slice(0,8)}-05:00`);minutesLate=Math.max(0,Math.floor((Date.now()-start.getTime())/60000));if(minutesLate>(settings?.entryToleranceMinutes||0))statusCode='LATE'}const statusId=await Model.statusId(companyId,statusCode);try{const mark=await Model.createMark({sheetId:event.sheetId,qrEventId:event.id,collaboratorId:collaborator.id,markingType:event.markingType,source:'qr',statusId,minutesLate,deviceInfo:data.deviceInfo,latitude:data.latitude,longitude:data.longitude,registeredBy:user.id});await Model.audit(companyId,event.sheetId,'qr_mark_success',user.id,collaborator.id,JSON.stringify({type:event.markingType,minutesLate}),data.deviceInfo,ip);return mark}catch(e){if(e.number===2601||e.number===2627)fail('Ya registraste esta marcación',409);throw e}}
 static async manual(id,data,companyId,user,ip){const sheet=await Model.getSheet(id,companyId);if(!sheet)fail('Tareo no encontrado',404);if(!['in_progress','reopened'].includes(sheet.status))fail('El tareo está cerrado',409);if(!data.collaboratorId||!data.markingType||!data.reason)fail('Selecciona colaborador, tipo y motivo');if(!await Model.isExpected(id,Number(data.collaboratorId)))fail('El colaborador no pertenece a este tareo');const statusId=await Model.statusId(companyId,'MANUAL_ENTRY');const mark=await Model.createMark({sheetId:id,collaboratorId:Number(data.collaboratorId),markingType:data.markingType,source:'manual',statusId,reason:data.reason,observation:data.observation,registeredBy:user.id});await Model.audit(companyId,id,'manual_mark',user.id,Number(data.collaboratorId),JSON.stringify(data),null,ip);return mark}
 static async validate(id,collaboratorId,data,companyId,user,ip){const sheet=await Model.getSheet(id,companyId);if(!sheet)fail('Tareo no encontrado',404);if(!['confirmed','observed','annulled','impersonation'].includes(data.validation))fail('Validación no válida');await Model.validateExpected(id,collaboratorId,data.validation,data.observation);await Model.audit(companyId,id,`visual_${data.validation}`,user.id,collaboratorId,data.observation,null,ip);return this.detail(id,companyId)}
 static async close(id,companyId,user,ip){const detail=await this.detail(id,companyId);if(!['in_progress','reopened'].includes(detail.sheet.status))fail('El tareo ya está cerrado',409);const pending=detail.people.filter(x=>!x.entryAt).length,exits=detail.people.filter(x=>x.entryAt&&!x.exitAt).length,observed=detail.people.filter(x=>x.supervisorValidation==='observed').length,absentId=await Model.statusId(companyId,'ABSENT');if(absentId)await Model.markAbsences(id,absentId);const sheet=await Model.setSheetStatus(id,companyId,'supervisor_closed',user.id,`Alertas al cierre: ${pending} faltas, ${exits} sin salida, ${observed} observados`);await Model.audit(companyId,id,'supervisor_closed',user.id,null,sheet.notes,null,ip);return{sheet,warnings:{pending,missingExits:exits,observed}}}
 static async review(id,data,companyId,user,ip){if(user.role!=='rrhh'&&user.role!=='admin')fail('Solo RRHH o Admin puede revisar tareos',403);const allowed=['rrhh_observed','rrhh_approved','reopened','cancelled'];if(!allowed.includes(data.status))fail('Estado de revisión no válido');const sheet=await Model.setSheetStatus(id,companyId,data.status,user.id,data.notes);await Model.audit(companyId,id,data.status,user.id,null,data.notes,null,ip);return sheet}
}
module.exports=AttendanceService
