const fs=require('fs'),path=require('path'),PDFDocument=require('pdfkit'),Model=require('../models/PersonnelProcessModel')
const fail=(message,status=400)=>{const e=new Error(message);e.status=status;throw e}
const date=value=>value?new Intl.DateTimeFormat('es-PE',{timeZone:'UTC'}).format(new Date(value)):''
class ContractDocumentService{
 static access(data,user){if(user?.role==='colaborador'&&data.collaboratorUserId!==user.id)fail('No tienes acceso a este contrato',403)}
 static replace(text,data){const values={empresa_razon_social:data.companyBusinessName,empresa_nombre_comercial:data.companyTradeName||data.companyBusinessName,empresa_ruc:data.companyTaxId||'',colaborador_nombre:`${data.firstName} ${data.lastName}`,documento_tipo:data.documentType,documento_numero:data.documentNumber,codigo_colaborador:data.employeeCode,cargo:data.positionName,tipo_vinculo:data.employmentTypeName,fecha_inicio:date(data.startDate),fecha_fin:date(data.endDate),numero_contrato:data.contractNumber};return String(text||'').replace(/\{\{([a-z_]+)\}\}/g,(match,key)=>values[key]??match).replace(/\\n/g,'\n')}
 static async generate(id,companyId){const data=await Model.getContractData(id,companyId);if(!data)fail('Contrato no encontrado',404);if(data.documentStatus==='signed')fail('El contrato firmado ya no puede regenerarse',409);if(!data.contractTemplateId||!data.bodyText)fail('Selecciona una plantilla para generar el contrato');const dir=path.join(process.cwd(),'uploads','contracts',String(companyId),'generated');fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,`contrato-${id}-${Date.now()}.pdf`),relative=path.relative(process.cwd(),file).replace(/\\/g,'/');await new Promise((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margins:{top:65,bottom:65,left:65,right:65},info:{Title:data.templateTitle,Author:data.companyBusinessName}}),stream=fs.createWriteStream(file);doc.pipe(stream);doc.font('Helvetica-Bold').fontSize(16).text(this.replace(data.templateTitle,data),{align:'center'});doc.moveDown(2);doc.font('Helvetica').fontSize(11).text(this.replace(data.bodyText,data),{align:'justify',lineGap:5});doc.moveDown(4);doc.text('____________________________                ____________________________',{align:'center'});doc.text(`${data.companyBusinessName}                                    ${data.firstName} ${data.lastName}`,{align:'center'});if(data.footerText){doc.moveDown(3);doc.fontSize(9).fillColor('#555').text(this.replace(data.footerText,data),{align:'center'})}doc.end();stream.on('finish',resolve);stream.on('error',reject)});if(data.generatedPdfPath){const previous=path.resolve(process.cwd(),data.generatedPdfPath);if(previous!==file&&previous.startsWith(path.resolve(process.cwd(),'uploads')+path.sep))fs.promises.unlink(previous).catch(()=>{})}await Model.setGeneratedPdf(id,companyId,relative);return file}
 static async generated(id,companyId,user){const data=await Model.getContractData(id,companyId);if(!data)fail('Contrato no encontrado',404);this.access(data,user);if(!data.generatedPdfPath)fail('El contrato aún no ha sido generado',404);const file=path.resolve(process.cwd(),data.generatedPdfPath);if(!fs.existsSync(file))fail('Archivo PDF no encontrado',404);return file}
 static async signed(id,companyId,file,user){const data=await Model.getContractData(id,companyId);if(!data)fail('Contrato no encontrado',404);this.access(data,user);if(data.documentStatus==='signed')fail('El contrato ya fue confirmado como firmado',409);if(!file)fail('Selecciona el PDF firmado');const relative=path.relative(process.cwd(),file.path).replace(/\\/g,'/');if(data.signedPdfPath){const previous=path.resolve(process.cwd(),data.signedPdfPath);if(previous.startsWith(path.resolve(process.cwd(),'uploads')+path.sep))fs.promises.unlink(previous).catch(()=>{})}await Model.setSignedPdf(id,companyId,relative);return Model.getById(id,companyId)}
 static async confirmSigned(id,companyId){const data=await Model.getContractData(id,companyId);if(!data)fail('Contrato no encontrado',404);if(data.documentStatus==='signed')return Model.getById(id,companyId);if(!data.signedPdfPath)fail('Carga primero el PDF firmado');return Model.confirmContractSigned(id,companyId)}
 static async signedFile(id,companyId,user){const data=await Model.getContractData(id,companyId);if(!data)fail('Contrato no encontrado',404);this.access(data,user);if(!data.signedPdfPath)fail('Aún no se cargó el contrato firmado',404);const file=path.resolve(process.cwd(),data.signedPdfPath);if(!fs.existsSync(file))fail('Archivo firmado no encontrado',404);return file}
}
module.exports=ContractDocumentService
