const { poolPromise, sql } = require('../config/db')
class AttendanceModel {
  static async list(companyId) { const pool=await poolPromise; const r=await pool.request().input('companyId',sql.Int,companyId).query(`SELECT s.*,COALESCE(c.tradeName,c.businessName) clientName,st.name siteName,a.name areaName,sh.name shiftName,u.name supervisorName,(SELECT COUNT(*) FROM dbo.AttendanceExpected e WHERE e.sheetId=s.id) expectedCount,(SELECT COUNT(DISTINCT m.collaboratorId) FROM dbo.AttendanceMarks m WHERE m.sheetId=s.id AND m.estado=1) markedCount FROM dbo.AttendanceSheets s JOIN dbo.Clients c ON c.id=s.clientId JOIN dbo.Sites st ON st.id=s.siteId JOIN dbo.Areas a ON a.id=s.areaId JOIN dbo.Shifts sh ON sh.id=s.shiftId JOIN dbo.Users u ON u.id=s.supervisorId WHERE s.companyId=@companyId ORDER BY s.attendanceDate DESC,s.id DESC`);return r.recordset }
  static async getSheet(id,companyId){const pool=await poolPromise;const r=await pool.request().input('id',sql.Int,id).input('companyId',sql.Int,companyId).query(`SELECT s.*,sh.startTime,sh.endTime,COALESCE(c.tradeName,c.businessName) clientName,st.name siteName,a.name areaName,sh.name shiftName,u.name supervisorName FROM dbo.AttendanceSheets s JOIN dbo.Clients c ON c.id=s.clientId JOIN dbo.Sites st ON st.id=s.siteId JOIN dbo.Areas a ON a.id=s.areaId JOIN dbo.Shifts sh ON sh.id=s.shiftId JOIN dbo.Users u ON u.id=s.supervisorId WHERE s.id=@id AND s.companyId=@companyId`);return r.recordset[0]}
  static async createSheet(data,companyId,userId){const pool=await poolPromise;const tx=new sql.Transaction(pool);await tx.begin();try{const r=await new sql.Request(tx).input('companyId',sql.Int,companyId).input('clientId',sql.Int,data.clientId).input('siteId',sql.Int,data.siteId).input('areaId',sql.Int,data.areaId).input('shiftId',sql.Int,data.shiftId).input('date',sql.Date,data.attendanceDate).input('userId',sql.Int,userId).query(`INSERT dbo.AttendanceSheets(companyId,clientId,siteId,areaId,shiftId,attendanceDate,supervisorId,status) OUTPUT INSERTED.id VALUES(@companyId,@clientId,@siteId,@areaId,@shiftId,@date,@userId,N'in_progress')`);const id=r.recordset[0].id;await new sql.Request(tx).input('sheetId',sql.Int,id).input('companyId',sql.Int,companyId).input('siteId',sql.Int,data.siteId).input('areaId',sql.Int,data.areaId).input('shiftId',sql.Int,data.shiftId).input('date',sql.Date,data.attendanceDate).query(`INSERT dbo.AttendanceExpected(sheetId,collaboratorId) SELECT DISTINCT @sheetId,x.collaboratorId FROM dbo.CollaboratorAssignments x JOIN dbo.Collaborators c ON c.id=x.collaboratorId WHERE x.companyId=@companyId AND x.siteId=@siteId AND x.areaId=@areaId AND x.shiftId=@shiftId AND x.estado=1 AND c.estado=1 AND x.startDate<=@date AND (x.endDate IS NULL OR x.endDate>=@date)`);await tx.commit();return this.getSheet(id,companyId)}catch(e){await tx.rollback();throw e}}
  static async expected(sheetId,companyId){const pool=await poolPromise;const r=await pool.request().input('sheetId',sql.Int,sheetId).input('companyId',sql.Int,companyId).query(`SELECT e.id,e.collaboratorId,e.supervisorValidation,e.observation,c.employeeCode,c.firstName,c.lastName,p.name positionName,ast.code statusCode,ast.name statusName,(SELECT MIN(markedAt) FROM dbo.AttendanceMarks m WHERE m.sheetId=e.sheetId AND m.collaboratorId=e.collaboratorId AND m.markingType=N'entry' AND m.estado=1) entryAt,(SELECT MAX(markedAt) FROM dbo.AttendanceMarks m WHERE m.sheetId=e.sheetId AND m.collaboratorId=e.collaboratorId AND m.markingType=N'exit' AND m.estado=1) exitAt FROM dbo.AttendanceExpected e JOIN dbo.AttendanceSheets s ON s.id=e.sheetId JOIN dbo.Collaborators c ON c.id=e.collaboratorId JOIN dbo.Positions p ON p.id=c.positionId LEFT JOIN dbo.AttendanceStatuses ast ON ast.id=e.attendanceStatusId WHERE e.sheetId=@sheetId AND s.companyId=@companyId ORDER BY c.lastName,c.firstName`);return r.recordset}
  static async settings(companyId){const pool=await poolPromise;const r=await pool.request().input('companyId',sql.Int,companyId).query(`SELECT s.*,(SELECT TOP 1 entryToleranceMinutes FROM dbo.ToleranceRules t WHERE t.companyId=@companyId AND t.estado=1 ORDER BY t.id) entryToleranceMinutes FROM dbo.AttendanceSettings s WHERE s.companyId=@companyId`);return r.recordset[0]}
  static async createQr(sheetId,type,hash,expiresAt,userId){const pool=await poolPromise;await pool.request().input('sheetId',sql.Int,sheetId).query(`UPDATE dbo.AttendanceQrEvents SET active=0,closedAt=SYSUTCDATETIME() WHERE sheetId=@sheetId AND active=1`);const r=await pool.request().input('sheetId',sql.Int,sheetId).input('type',sql.NVarChar(20),type).input('hash',sql.Char(64),hash).input('expires',sql.DateTime2,expiresAt).input('userId',sql.Int,userId).query(`INSERT dbo.AttendanceQrEvents(sheetId,markingType,tokenHash,expiresAt,createdBy) OUTPUT INSERTED.id VALUES(@sheetId,@type,@hash,@expires,@userId)`);return r.recordset[0]}
  static async qrByHash(hash){const pool=await poolPromise;const r=await pool.request().input('hash',sql.Char(64),hash).query(`SELECT q.*,s.companyId,s.status sheetStatus,s.attendanceDate,s.clientId,s.siteId,s.areaId,s.shiftId,sh.startTime,sh.endTime FROM dbo.AttendanceQrEvents q JOIN dbo.AttendanceSheets s ON s.id=q.sheetId JOIN dbo.Shifts sh ON sh.id=s.shiftId WHERE q.tokenHash=@hash`);return r.recordset[0]}
  static async collaboratorByUser(userId,companyId){const pool=await poolPromise;const r=await pool.request().input('userId',sql.Int,userId).input('companyId',sql.Int,companyId).query(`SELECT * FROM dbo.Collaborators WHERE userId=@userId AND companyId=@companyId`);return r.recordset[0]}
  static async isExpected(sheetId,collaboratorId){const pool=await poolPromise;const r=await pool.request().input('sheetId',sql.Int,sheetId).input('collaboratorId',sql.Int,collaboratorId).query(`SELECT id FROM dbo.AttendanceExpected WHERE sheetId=@sheetId AND collaboratorId=@collaboratorId`);return Boolean(r.recordset[0])}
  static async statusId(companyId,code){const pool=await poolPromise;const r=await pool.request().input('companyId',sql.Int,companyId).input('code',sql.NVarChar(30),code).query(`SELECT id FROM dbo.AttendanceStatuses WHERE companyId=@companyId AND code=@code AND estado=1`);return r.recordset[0]?.id}
  static async createMark(data){const pool=await poolPromise;const r=await pool.request().input('sheetId',sql.Int,data.sheetId).input('eventId',sql.Int,data.qrEventId||null).input('collaboratorId',sql.Int,data.collaboratorId).input('type',sql.NVarChar(20),data.markingType).input('source',sql.NVarChar(20),data.source).input('statusId',sql.Int,data.statusId||null).input('minutesLate',sql.Int,data.minutesLate??null).input('reason',sql.NVarChar(250),data.reason||null).input('observation',sql.NVarChar(500),data.observation||null).input('device',sql.NVarChar(250),data.deviceInfo||null).input('lat',sql.Decimal(9,6),data.latitude||null).input('lng',sql.Decimal(9,6),data.longitude||null).input('userId',sql.Int,data.registeredBy).query(`INSERT dbo.AttendanceMarks(sheetId,qrEventId,collaboratorId,markingType,source,attendanceStatusId,minutesLate,reason,observation,deviceInfo,latitude,longitude,registeredBy) OUTPUT INSERTED.* VALUES(@sheetId,@eventId,@collaboratorId,@type,@source,@statusId,@minutesLate,@reason,@observation,@device,@lat,@lng,@userId);UPDATE dbo.AttendanceExpected SET attendanceStatusId=@statusId WHERE sheetId=@sheetId AND collaboratorId=@collaboratorId`);return r.recordset[0]}
  static async validateExpected(sheetId,collaboratorId,validation,observation){const pool=await poolPromise;await pool.request().input('sheetId',sql.Int,sheetId).input('collaboratorId',sql.Int,collaboratorId).input('validation',sql.NVarChar(20),validation).input('observation',sql.NVarChar(500),observation||null).query(`UPDATE dbo.AttendanceExpected SET supervisorValidation=@validation,observation=@observation WHERE sheetId=@sheetId AND collaboratorId=@collaboratorId`)}
  static async markAbsences(sheetId,statusId){const pool=await poolPromise;await pool.request().input('sheetId',sql.Int,sheetId).input('statusId',sql.Int,statusId).query(`UPDATE e SET attendanceStatusId=@statusId FROM dbo.AttendanceExpected e WHERE e.sheetId=@sheetId AND NOT EXISTS(SELECT 1 FROM dbo.AttendanceMarks m WHERE m.sheetId=e.sheetId AND m.collaboratorId=e.collaboratorId AND m.markingType=N'entry' AND m.estado=1)`)}
  static async setSheetStatus(id,companyId,status,userId,notes){const pool=await poolPromise;await pool.request().input('id',sql.Int,id).input('companyId',sql.Int,companyId).input('status',sql.NVarChar(30),status).input('userId',sql.Int,userId).input('notes',sql.NVarChar(500),notes||null).query(`UPDATE dbo.AttendanceSheets SET status=@status,notes=COALESCE(@notes,notes),closedAt=CASE WHEN @status=N'supervisor_closed' THEN SYSUTCDATETIME() ELSE closedAt END,reviewedBy=CASE WHEN @status IN(N'rrhh_observed',N'rrhh_approved',N'reopened',N'cancelled') THEN @userId ELSE reviewedBy END,reviewedAt=CASE WHEN @status IN(N'rrhh_observed',N'rrhh_approved',N'reopened',N'cancelled') THEN SYSUTCDATETIME() ELSE reviewedAt END,updatedAt=SYSUTCDATETIME() WHERE id=@id AND companyId=@companyId`);return this.getSheet(id,companyId)}
  static async audit(companyId,sheetId,action,userId,collaboratorId,detail,device,ip){const pool=await poolPromise;await pool.request().input('companyId',sql.Int,companyId).input('sheetId',sql.Int,sheetId||null).input('action',sql.NVarChar(60),action).input('userId',sql.Int,userId).input('collaboratorId',sql.Int,collaboratorId||null).input('detail',sql.NVarChar(1000),detail||null).input('device',sql.NVarChar(250),device||null).input('ip',sql.NVarChar(64),ip||null).query(`INSERT dbo.AttendanceAudit(companyId,sheetId,action,userId,collaboratorId,detail,deviceInfo,ipAddress) VALUES(@companyId,@sheetId,@action,@userId,@collaboratorId,@detail,@device,@ip)`)}
}
module.exports=AttendanceModel
