const{poolPromise,sql}=require('../config/db');
class BonusModel{
 static async types(c){const p=await poolPromise,r=await p.request().input('c',sql.Int,c).query(`SELECT * FROM dbo.BonusTypes WHERE companyId=@c AND estado=1`);return r.recordset}
 static async rules(c){const p=await poolPromise,r=await p.request().input('c',sql.Int,c).query(`SELECT r.*,a.name areaName,t.name bonusTypeName,t.code bonusTypeCode FROM dbo.BonusRules r JOIN dbo.Areas a ON a.id=r.areaId JOIN dbo.BonusTypes t ON t.id=r.bonusTypeId WHERE r.companyId=@c ORDER BY r.id DESC`);return r.recordset}
 static async periods(c){const p=await poolPromise,r=await p.request().input('c',sql.Int,c).query(`SELECT bp.*,(SELECT COUNT(*) FROM dbo.BonusCampaigns bc WHERE bc.periodId=bp.id AND bc.status<>N'cancelled') campaignCount FROM dbo.BonusPeriods bp WHERE bp.companyId=@c AND bp.status<>N'cancelled' ORDER BY bp.periodStart DESC`);return r.recordset}
 static async settings(c){const p=await poolPromise,r=await p.request().input('c',sql.Int,c).query(`SELECT * FROM dbo.BonusSettings WHERE companyId=@c`);return r.recordset[0]}
 static async updateSettings(c,u,d){const p=await poolPromise,r=await p.request().input('c',sql.Int,c).input('u',sql.Int,u).input('f',sql.NVarChar(20),d.paymentFrequency).input('day',sql.Int,d.cutoffDay||15).query(`UPDATE dbo.BonusSettings SET paymentFrequency=@f,cutoffDay=@day,updatedBy=@u,updatedAt=SYSUTCDATETIME() OUTPUT INSERTED.* WHERE companyId=@c`);return r.recordset[0]}
 static async createPeriod(c,u,d){const p=await poolPromise,r=await p.request().input('c',sql.Int,c).input('u',sql.Int,u).input('n',sql.NVarChar(100),d.name).input('ps',sql.Date,d.periodStart).input('pe',sql.Date,d.periodEnd).input('f',sql.NVarChar(20),d.frequency).query(`INSERT dbo.BonusPeriods(companyId,name,periodStart,periodEnd,status,frequency,createdBy) OUTPUT INSERTED.* VALUES(@c,@n,@ps,@pe,N'open',@f,@u)`);return r.recordset[0]}
 static async setPeriodStatus(id,c,u,status){const p=await poolPromise,r=await p.request().input('id',sql.Int,id).input('c',sql.Int,c).input('u',sql.Int,u).input('st',sql.NVarChar(20),status).query(`UPDATE dbo.BonusPeriods SET status=@st,closedBy=CASE WHEN @st=N'closed' THEN @u ELSE NULL END,closedAt=CASE WHEN @st=N'closed' THEN SYSUTCDATETIME() ELSE NULL END,updatedAt=SYSUTCDATETIME() OUTPUT INSERTED.* WHERE id=@id AND companyId=@c`);return r.recordset[0]}
 static async campaigns(c){const p=await poolPromise,r=await p.request().input('c',sql.Int,c).query(`SELECT x.*,bp.name periodName,bp.status periodStatus,cl.name clientName,s.name siteName,a.name areaName,t.name bonusTypeName,r.name ruleName FROM dbo.BonusCampaigns x JOIN dbo.BonusPeriods bp ON bp.id=x.periodId JOIN dbo.Clients cl ON cl.id=x.clientId JOIN dbo.Sites s ON s.id=x.siteId JOIN dbo.Areas a ON a.id=x.areaId JOIN dbo.BonusTypes t ON t.id=x.bonusTypeId JOIN dbo.BonusRules r ON r.id=x.ruleId WHERE x.companyId=@c ORDER BY bp.periodStart DESC,x.id DESC`);return r.recordset}
 static async createRule(c,u,d){const p=await poolPromise,r=await p.request().input('c',sql.Int,c).input('u',sql.Int,u).input('a',sql.Int,d.areaId).input('t',sql.Int,d.bonusTypeId).input('n',sql.NVarChar(120),d.name).input('m',sql.NVarChar(20),d.calculationMode).input('bs',sql.NVarChar(30),d.baseSource||'salary').input('f',sql.Decimal(12,2),d.fixedAmount||null).input('pc',sql.Decimal(7,4),d.percentage||null).input('mb',sql.Decimal(12,2),d.monthlyBonusBase||null).input('ad',sql.Int,d.minAttendanceDays||0).input('ab',sql.Int,d.maxAbsences||0).input('lt',sql.Int,d.maxLateArrivals||0).input('sn',sql.Int,d.minSeniorityDays||0).input('ew',sql.Int,d.entryWindowDays||30).input('pmin',sql.Decimal(5,2),d.productivityMin??null).input('pmax',sql.Decimal(5,2),d.productivityMax??null).input('vf',sql.Date,d.validFrom).input('vt',sql.Date,d.validTo||null).input('st',sql.NVarChar(20),d.ruleStatus||'draft').query(`INSERT dbo.BonusRules(companyId,areaId,bonusTypeId,name,calculationMode,baseSource,fixedAmount,percentage,monthlyBonusBase,minAttendanceDays,maxAbsences,maxLateArrivals,minSeniorityDays,entryWindowDays,productivityMin,productivityMax,validFrom,validTo,ruleStatus,createdBy) OUTPUT INSERTED.* VALUES(@c,@a,@t,@n,@m,@bs,@f,@pc,@mb,@ad,@ab,@lt,@sn,@ew,@pmin,@pmax,@vf,@vt,@st,@u)`);return r.recordset[0]}
 static async createCampaign(c,u,d){const p=await poolPromise,r=await p.request().input('c',sql.Int,c).input('u',sql.Int,u).input('n',sql.NVarChar(150),d.name).input('p',sql.Int,d.periodId).input('cl',sql.Int,d.clientId).input('s',sql.Int,d.siteId).input('a',sql.Int,d.areaId).input('t',sql.Int,d.bonusTypeId).input('r',sql.Int,d.ruleId).query(`INSERT dbo.BonusCampaigns(companyId,name,periodId,periodStart,periodEnd,clientId,siteId,areaId,bonusTypeId,ruleId,status,createdBy) OUTPUT INSERTED.* SELECT @c,@n,bp.id,bp.periodStart,bp.periodEnd,@cl,@s,@a,@t,@r,N'active',@u FROM dbo.BonusPeriods bp WHERE bp.id=@p AND bp.companyId=@c AND bp.status=N'open'`);return r.recordset[0]}
 static async detail(id,c){const p=await poolPromise,r=await p.request().input('id',sql.Int,id).input('c',sql.Int,c).query(`SELECT x.*,bp.name periodName,bp.status periodStatus,r.calculationMode,r.baseSource,r.fixedAmount,r.percentage,r.monthlyBonusBase,r.minAttendanceDays,r.maxAbsences,r.maxLateArrivals,r.minSeniorityDays,r.entryWindowDays,r.productivityMin,r.productivityMax,r.validFrom ruleValidFrom,r.validTo ruleValidTo,r.ruleStatus,bt.code bonusTypeCode FROM dbo.BonusCampaigns x JOIN dbo.BonusPeriods bp ON bp.id=x.periodId JOIN dbo.BonusRules r ON r.id=x.ruleId JOIN dbo.BonusTypes bt ON bt.id=x.bonusTypeId WHERE x.id=@id AND x.companyId=@c;SELECT br.*,co.employeeCode,co.firstName,co.lastName FROM dbo.BonusResults br JOIN dbo.Collaborators co ON co.id=br.collaboratorId WHERE br.campaignId=@id ORDER BY co.lastName`);return{campaign:r.recordsets[0][0],results:r.recordsets[1]}}
}
module.exports=BonusModel;
