const{poolPromise,sql}=require('../config/db')
class ContractTemplateModel{
 static async getAll(companyId,includeInactive=false){const pool=await poolPromise,r=await pool.request().input('companyId',sql.Int,companyId).input('all',sql.Bit,includeInactive).query(`SELECT * FROM dbo.ContractTemplates WHERE companyId=@companyId AND (@all=1 OR estado=1) ORDER BY isDefault DESC,name`);return r.recordset}
 static async getById(id,companyId){const pool=await poolPromise,r=await pool.request().input('id',sql.Int,id).input('companyId',sql.Int,companyId).query(`SELECT * FROM dbo.ContractTemplates WHERE id=@id AND companyId=@companyId`);return r.recordset[0]}
 static bind(req,data){return req.input('code',sql.NVarChar(30),data.code).input('name',sql.NVarChar(120),data.name).input('title',sql.NVarChar(200),data.title).input('bodyText',sql.NVarChar(sql.MAX),data.bodyText).input('footerText',sql.NVarChar(500),data.footerText||null).input('isDefault',sql.Bit,data.isDefault??0).input('estado',sql.Bit,data.estado??1)}
 static async create(companyId,data){const pool=await poolPromise;if(data.isDefault)await pool.request().input('companyId',sql.Int,companyId).query(`UPDATE dbo.ContractTemplates SET isDefault=0 WHERE companyId=@companyId`);const r=await this.bind(pool.request().input('companyId',sql.Int,companyId),data).query(`INSERT dbo.ContractTemplates(companyId,code,name,title,bodyText,footerText,isDefault,estado) OUTPUT INSERTED.* VALUES(@companyId,@code,@name,@title,@bodyText,@footerText,@isDefault,@estado)`);return r.recordset[0]}
 static async update(id,companyId,data){const pool=await poolPromise;if(data.isDefault)await pool.request().input('companyId',sql.Int,companyId).query(`UPDATE dbo.ContractTemplates SET isDefault=0 WHERE companyId=@companyId`);const r=await this.bind(pool.request().input('id',sql.Int,id).input('companyId',sql.Int,companyId),data).query(`UPDATE dbo.ContractTemplates SET code=@code,name=@name,title=@title,bodyText=@bodyText,footerText=@footerText,isDefault=@isDefault,estado=@estado,updatedAt=SYSUTCDATETIME() OUTPUT INSERTED.* WHERE id=@id AND companyId=@companyId`);return r.recordset[0]}
}
module.exports=ContractTemplateModel
