const { poolPromise, sql } = require('../config/db');
class HolidayModel {
  static async getPolicy(companyId){const pool=await poolPromise;const r=await pool.request().input('companyId',sql.Int,companyId).query('SELECT companyId,surchargePercent,allowSubstituteRest,useShiftStartDate,updatedAt FROM dbo.HolidayPolicies WHERE companyId=@companyId');return r.recordset[0]}
  static async updatePolicy(companyId,data){const pool=await poolPromise;await pool.request().input('companyId',sql.Int,companyId).input('surcharge',sql.Decimal(5,2),data.surchargePercent).input('substitute',sql.Bit,data.allowSubstituteRest).input('shiftStart',sql.Bit,data.useShiftStartDate).query(`UPDATE dbo.HolidayPolicies SET surchargePercent=@surcharge,allowSubstituteRest=@substitute,useShiftStartDate=@shiftStart,updatedAt=SYSUTCDATETIME() WHERE companyId=@companyId`);return this.getPolicy(companyId)}
  static async getAll(companyId,year){const pool=await poolPromise;const r=await pool.request().input('companyId',sql.Int,companyId).input('year',sql.Int,year).query(`SELECT h.id,h.holidayDate,h.name,h.dayType,h.scope,h.isPaid,h.surchargePercent,h.allowSubstituteRest,h.notes,h.estado,COALESCE(h.surchargePercent,p.surchargePercent) effectiveSurchargePercent,COALESCE(h.allowSubstituteRest,p.allowSubstituteRest) effectiveAllowSubstituteRest FROM dbo.Holidays h INNER JOIN dbo.HolidayPolicies p ON p.companyId=h.companyId WHERE h.companyId=@companyId AND YEAR(h.holidayDate)=@year ORDER BY h.holidayDate`);return r.recordset}
  static async getById(id,companyId){const pool=await poolPromise;const r=await pool.request().input('id',sql.Int,id).input('companyId',sql.Int,companyId).query('SELECT id,holidayDate,name,dayType,scope,isPaid,surchargePercent,allowSubstituteRest,notes,estado FROM dbo.Holidays WHERE id=@id AND companyId=@companyId');return r.recordset[0]}
  static bind(request,data){return request.input('date',sql.Date,data.holidayDate).input('name',sql.NVarChar(150),data.name).input('dayType',sql.NVarChar(20),data.dayType).input('scope',sql.NVarChar(20),data.scope).input('isPaid',sql.Bit,data.isPaid).input('surcharge',sql.Decimal(5,2),data.surchargePercent??null).input('substitute',sql.Bit,data.allowSubstituteRest??null).input('notes',sql.NVarChar(500),data.notes||null).input('estado',sql.Bit,data.estado??1)}
  static async create(companyId,data){const pool=await poolPromise;const req=this.bind(pool.request().input('companyId',sql.Int,companyId),data);const r=await req.query(`INSERT dbo.Holidays(companyId,holidayDate,name,dayType,scope,isPaid,surchargePercent,allowSubstituteRest,notes,estado) OUTPUT INSERTED.id VALUES(@companyId,@date,@name,@dayType,@scope,@isPaid,@surcharge,@substitute,@notes,@estado)`);return this.getById(r.recordset[0].id,companyId)}
  static async update(id,companyId,data){const pool=await poolPromise;const req=this.bind(pool.request().input('id',sql.Int,id).input('companyId',sql.Int,companyId),data);await req.query(`UPDATE dbo.Holidays SET holidayDate=@date,name=@name,dayType=@dayType,scope=@scope,isPaid=@isPaid,surchargePercent=@surcharge,allowSubstituteRest=@substitute,notes=@notes,estado=@estado,updatedAt=SYSUTCDATETIME() WHERE id=@id AND companyId=@companyId`);return this.getById(id,companyId)}
}
module.exports=HolidayModel;
